Repository SYSOUT-org/CS-Study, pull requests merged in 2025-01, with the labels that each got.

#12 2025-01-06 [데이터베이스] Transaction
  데이터베이스/Transaction/myeongin-Transaction.md
Labels: 🤴진명인, 📚데이터베이스

#6 2025-01-06 [데이터베이스] Transaction
  데이터베이스/Transaction/Shanate-Transaction.md
Labels: 👨‍🦰신재혁, 📚데이터베이스

#7 2025-01-05 [데이터베이스] Transaction
  데이터베이스/Transaction/sapientia1007-Transaction.md
Labels: 👸심지혜, 📚데이터베이스

#3 2025-01-05 [데이터베이스] Transaction
  데이터베이스/Transaction/weejinyoung-Transaction.md
Labels: 👨위진영, 📚데이터베이스

#10 2025-01-05 [데이터베이스] Transaction
  데이터베이스/Transaction/harvartz-Transaction.md
Labels: 🧒양석진, 📚데이터베이스

#11 2025-01-06 [데이터베이스] Transaction
  데이터베이스/Transaction/Jungjuhyeon-Transaction.md
Labels: 👱‍♂️정주현, 📚데이터베이스

#8 2025-01-05 [데이터베이스] Transaction
  데이터베이스/Transaction/kyko-Transaction.md
Labels: 👦고경남, 📚데이터베이스

#4 2025-01-05 [데이터베이스] Transaction
  .idea/misc.xml
  데이터베이스/Transaction/heogeonho-Transaction.md
Labels: 🧔허건호, 📚데이터베이스

#17 2025-01-13 [데이터베이스] Normalization
  데이터베이스/Normalization/Shanate-Normalization.md
Labels: 👨‍🦰신재혁, 📚데이터베이스

#25 2025-01-13 [운영체제] 프로세스와 스레드
  운영체제/process/processAndTread.md
Labels: 🤴진명인, 🧒양석진, 👨위진영, 👱‍♂️정주현, 🧩운영체제

#21 2025-01-13 [데이터베이스] Nomalization
  데이터베이스/Normalization/harvartz-Normalization.md
Labels: 🧒양석진, 📚데이터베이스

#16 2025-01-11 [데이터베이스] Normalization
  데이터베이스/Normalization/sapientia1007-Normalization.md
Labels: 👸심지혜, 📚데이터베이스

#13 2025-01-11 [데이터베이스] Normalization
  데이터베이스/Normalization/myeongin-Normalization.md
Labels: 🤴진명인, 📚데이터베이스

#14 2025-01-11 [데이터베이스] Normalization
  데이터베이스/Normalization/kyko-Normalization.md
Labels: 👦고경남, 📚데이터베이스

#23 2025-01-13 [컴퓨터 구조] CPU와 메모리
  컴퓨터 구조/CPU와 메모리/kyko_team_CPU_Memory
Labels: 👨‍🦰신재혁, 👦고경남, 🧔허건호, 👸심지혜, 💾컴퓨터구조

#15 2025-01-11 [데이터베이스] Normalization
  데이터베이스/Normalization/dhfkdlsj-Normalization.md
Labels: 🧓강희준, 📚데이터베이스

#18 2025-01-13 [데이터베이스] Normalization
  데이터베이스/Normalization/Jungjuhyeon-Normalization.md
Labels: 👱‍♂️정주현, 📚데이터베이스

#22 2025-01-11 [데이터베이스] Normalization
  데이터베이스/Normalization/alexization-Normalization.md
Labels: 👶백효석, 📚데이터베이스

#24 2025-01-13 [데이터베이스] 인덱스
  데이터베이스/Index/dhfkdlsj_team_Index.md
Labels: 👨‍🦱이승훈, 👶백효석, 🧓강희준, 👩‍🦰조민정, 📚데이터베이스

#20 2025-01-13 [데이터베이스] Nomalization
  데이터베이스/Normalization/lsh981127-Normalization.md
Labels: 👨‍🦱이승훈, 📚데이터베이스
